# analysis_options.yaml - Configuración para BLE SOS App
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  
  errors:
    # ✅ ERRORES CRÍTICOS - Siempre mostrar
    undefined_function: error
    undefined_method: error
    undefined_getter: error
    undefined_setter: error
    invalid_assignment: error
    argument_type_not_assignable: error
    
    # ✅ DUPLICADOS - Siempre mostrar  
    duplicate_definition: error
    duplicate_import: error
    
    # ✅ IMPORTS - Siempre mostrar
    unused_import: warning
    missing_required_param: error
    
    # 🔕 SUPRIMIR warnings molestos
    avoid_print: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    
linter:
  rules:
    # ✅ REGLAS CRÍTICAS - Mantener activas
    - avoid_empty_else
    - avoid_returning_null_for_future
    - cancel_subscriptions
    - close_sinks
    - control_flow_in_finally
    - empty_statements
    - hash_and_equals
    - invariant_booleans
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - prefer_void_to_null
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_statements
    - unrelated_type_equality_checks
    - valid_regexps
    
    # 🔕 REGLAS DESHABILITADAS para desarrollo más fluido
    - avoid_print: false
    - prefer_const_constructors: false
    - prefer_const_literals_to_create_immutables: false
    - prefer_final_fields: false
    - use_build_context_synchronously: false
    - prefer_interpolation_to_compose_strings: false
    - unnecessary_null_comparison: false
    - avoid_unnecessary_containers: false
    
    # ✅ REGLAS ÚTILES - Mantener activas pero como warnings
    - unused_local_variable
    - unused_field
    - dead_code